# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6491831556baba9d7a915bd50bef7dbc6ee73c32cbfb2a6e07582bb32c86d09e4adeee334f6edd84585f04e3ec13712887bef878bcf13a3b2a5f1eba2009b2b0

test:
  secret_key_base: f8dd553460c3160845530c614ba045383fb47a28320328eeca8486c5aac27fd755e2206f04cbaef96049ed8041ffa18adef908c3649c1a2bdbc201558747caa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
